In [ ]:
#NUMPY

In [1]:
import numpy as np


In [2]:
a=np.array([[1,2,4,5],[6,7,8,9],[10,11,3,12]])

In [3]:
print (a[0])

[1 2 4 5]


In [4]:
np.zeros(2)

array([0., 0.])

In [5]:
np.ones(3)

array([1., 1., 1.])

In [7]:
np.twos(3)

AttributeError: module 'numpy' has no attribute 'twos'

In [14]:
np.arange(4)

array([0, 1, 2, 3])

In [9]:
np.empty(3)

array([1., 1., 1.])

In [11]:
print(np.arrange(4))

AttributeError: module 'numpy' has no attribute 'arrange'

In [13]:
np.arange(4)

array([0, 1, 2, 3])

In [15]:
b=np.array([1,2,3,4,5,6,7,8])

In [16]:
np.append(b,[9,0])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [17]:
np.delete(b,2)

array([1, 2, 4, 5, 6, 7, 8])

In [18]:
np.sort(b)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
b.ndim

1

In [23]:
b.size

8

In [24]:
b.shape

(8,)

In [49]:
c=np.array([[[1,2,4,5],
           [6,7,8,9]],
           [[10,11,3,12],
           [11,12,14,15]],
            [[2,3,5,7],
            [2,5,3,6]]])

In [28]:
c.ndim

3

In [29]:
c.size

24

In [31]:
c.shape

(3, 2, 4)

In [34]:
d=c.reshape(4,2,3)

In [35]:
print(d)

[[[ 1  2  4]
  [ 5  6  7]]

 [[ 8  9 10]
  [11  3 12]]

 [[11 12 14]
  [15  2  3]]

 [[ 5  7  2]
  [ 5  3  6]]]


In [36]:
e=d[np.newaxis]

In [37]:
print(e)

[[[[ 1  2  4]
   [ 5  6  7]]

  [[ 8  9 10]
   [11  3 12]]

  [[11 12 14]
   [15  2  3]]

  [[ 5  7  2]
   [ 5  3  6]]]]


In [38]:
print (e[e>10])

[11 12 11 12 14 15]


In [39]:
habisbagi3=e[e%3==0]

In [40]:
print(habisbagi3)

[ 6  9  3 12 12 15  3  3  6]


In [45]:
np.hstack((e[e>10], habisbagi3))

array([11, 12, 11, 12, 14, 15,  6,  9,  3, 12, 12, 15,  3,  3,  6])

In [46]:
#####################

In [47]:
## BASIC ARRAY OPERATION

In [51]:
zeta=np.array([2,35,6,4,2])

In [52]:
zeta.sum()

49

In [58]:
#SHAPE : NDIM berarti menunjukkan dimensi 

kelas_063 = np.asarray([[1,2,3,5]])
kelas_064 = np.asarray([[2,3,4,5]])


In [78]:
kelas_gabungan= np.concatenate((kelas_063,kelas_064),axis=None)

In [79]:
print(kelas_gabungan)

[1 2 3 5 2 3 4 5]


In [80]:
zeta=np.array([2,35,6,4,2])

In [81]:
zeta*2

array([ 4, 70, 12,  8,  4])

In [83]:
zeta.max()

35

In [85]:
zeta2x = zeta*2

In [86]:
zeta2x.max()

70

In [87]:
print(d)

[[[ 1  2  4]
  [ 5  6  7]]

 [[ 8  9 10]
  [11  3 12]]

 [[11 12 14]
  [15  2  3]]

 [[ 5  7  2]
  [ 5  3  6]]]


In [88]:
print(d[0])

[[1 2 4]
 [5 6 7]]


In [89]:
print(d[0,1])

[5 6 7]


In [102]:
print(d[0,1,0])

5


In [91]:
x=d.flatten()

In [92]:
print(x)

[ 1  2  4  5  6  7  8  9 10 11  3 12 11 12 14 15  2  3  5  7  2  5  3  6]


In [96]:
f= np.array([[1,2,4,5],
           [6,7,8,9],
           [10,11,3,12],
           [11,12,14,15],
            [2,3,5,7],
            [2,5,3,6]])

In [98]:
f.shape

(6, 4)

In [99]:
print(f[0,2])

4
