<a href="https://colab.research.google.com/github/naavsaa/Hactiv8-Python/blob/master/Hactiv8/Pertemuan_13__Klasifikasi_2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#KNN, Naive Bayes, Decision Tree, Random Forest Algorithm, SVM

#mencari kesamaan berdasarkan kedekatan dari kategori2 yang ada

weather = ['Sunny','Sunny','Overcast','Rainy','Rainy',
           'Rainy','Overcast','Sunny','Sunny','Rainy',
           'Sunny','Overcast','Overcast','Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool',
        'Cool','Cool','Mild','Cool','Mild',
        'Mild','Mild','Hot','Mild']

play = ['No','No','Yes','Yes','Yes',
        'No','Yes','No','Yes','Yes',
        'Yes','Yes','Yes','No']


from sklearn import preprocessing

encode = preprocessing.LabelEncoder()
weather_encoded=encode.fit_transform(weather)
#Sunny = 2 , Overcast = 0 , Rainy = 1
print(weather_encoded)

#Mild = 2 , Hot = 1, Cool = 0
temp_encoded = encode.fit_transform(temp)
print(temp_encoded)

#No = 0, Yes = 1
play_encoded = encode.fit_transform(play)
label = play_encoded
print(play_encoded)

#zip encoder 
features = list(zip(weather_encoded,temp_encoded))
print(features)


[2 2 0 1 1 1 0 2 2 1 2 0 0 1]
[1 1 1 2 0 0 0 2 0 2 2 2 1 2]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]
[(2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2)]

____________________________________________________________

Berdasarkan model Machine Learning kita (KNN = 3)

Prediksi Machine Learning KNN dengan input 
cuaca Rainy,Overcast, dan Suhu Mild, Hot

1 = Play, 0 = No

[1] <- Play      (Overcast, dan Suhu Mild)
[1] <- Play      (Overcast, dan Suhu Hot)
[0] <- Not Play  (Rainy, dan Suhu Hot)
[1] <- Play      (Rainy, dan Suhu Mild)

____________________________________________________________




In [ ]:
#KNN
#Library yang perlu diingat
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=3)
model.fit(features,label)
predicted = model.predict([[0,2]])
print(f"""
____________________________________________________________

Berdasarkan model Machine Learning kita (KNN = 3)

Prediksi Machine Learning KNN dengan input 
cuaca Rainy,Overcast, dan Suhu Mild, Hot

1 = Play, 0 = No

{model.predict([[0,2]])} <- Play      (Overcast, dan Suhu Mild)
{model.predict([[0,1]])} <- Play      (Overcast, dan Suhu Hot)
{model.predict([[1,1]])} <- Not Play  (Rainy, dan Suhu Hot)
{model.predict([[1,2]])} <- Play      (Rainy, dan Suhu Mild)

____________________________________________________________

""")


____________________________________________________________

Berdasarkan model Machine Learning kita (KNN = 3)

Prediksi Machine Learning KNN dengan input 
cuaca Rainy,Overcast, dan Suhu Mild, Hot

1 = Play, 0 = No

[1] <- Play      (Overcast, dan Suhu Mild)
[1] <- Play      (Overcast, dan Suhu Hot)
[0] <- Not Play  (Rainy, dan Suhu Hot)
[1] <- Play      (Rainy, dan Suhu Mild)

____________________________________________________________




In [ ]:
#Naive Bayes
#Library yang perlu diingat
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(features,label)
predicted = model.predict([[0,2]])
print(f"""
____________________________________________________________

Berdasarkan model Naive Bayes kita ()

Prediksi Machine Learning Naive Bayes dengan input 
cuaca Rainy,Overcast, dan Suhu Mild, Hot

1 = Play, 0 = No

{model.predict([[0,2]])} <- Play      (Overcast, dan Suhu Mild)
{model.predict([[0,1]])} <- Play      (Overcast, dan Suhu Hot)
{model.predict([[1,1]])} <- Play      (Rainy, dan Suhu Hot)
{model.predict([[1,2]])} <- Play      (Rainy, dan Suhu Mild)

____________________________________________________________

""")


____________________________________________________________

Berdasarkan model Naive Bayes kita ()

Prediksi Machine Learning Naive Bayes dengan input 
cuaca Rainy,Overcast, dan Suhu Mild, Hot

1 = Play, 0 = No

[1] <- Play      (Overcast, dan Suhu Mild)
[1] <- Play      (Overcast, dan Suhu Hot)
[1] <- Play  (Rainy, dan Suhu Hot)
[1] <- Play      (Rainy, dan Suhu Mild)

____________________________________________________________




In [ ]:
#Decision Tree
#Library yang perlu diingat
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

X = features
y = label

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.5, random_state=1)

model = DecisionTreeClassifier()
model = model.fit(X_train,y_train)
y_pred = model.predict(X_test)

print(f"""
____________________________________________________________

Berdasarkan model Decision Tree kita ()

Prediksi Machine Learning Decision Tree dengan input 
cuaca Rainy,Overcast, dan Suhu Mild, Hot

1 = Play, 0 = No

{model.predict([[0,2]])} <- Play      (Overcast, dan Suhu Mild)
{model.predict([[0,1]])} <- Play      (Overcast, dan Suhu Hot)
{model.predict([[1,1]])} <- Not Play  (Rainy, dan Suhu Hot)
{model.predict([[1,2]])} <- Not Play  (Rainy, dan Suhu Mild)

____________________________________________________________

""")


____________________________________________________________

Berdasarkan model Decision Tree kita ()

Prediksi Machine Learning Decision Tree dengan input 
cuaca Rainy,Overcast, dan Suhu Mild, Hot

1 = Play, 0 = No

[1] <- Play      (Overcast, dan Suhu Mild)
[1] <- Play      (Overcast, dan Suhu Hot)
[0] <- Not Play  (Rainy, dan Suhu Hot)
[0] <- Not Play  (Rainy, dan Suhu Mild)

____________________________________________________________




In [ ]:
#Random Forest (kumpulan dari decision tree)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

X = features
y = label

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.5, random_state=1)

model = RandomForestClassifier(n_estimators=10)
model = model.fit(X_train,y_train)
y_pred = model.predict(X_test)

print(f"""
____________________________________________________________

Berdasarkan model Random Forest kita (n_estimator =10)

Prediksi Machine Learning Random Fores dengan input 
cuaca Rainy,Overcast, dan Suhu Mild, Hot

1 = Play, 0 = No

{model.predict([[0,2]])} <- Play      (Overcast, dan Suhu Mild)
{model.predict([[0,1]])} <- Play      (Overcast, dan Suhu Hot)
{model.predict([[1,1]])} <- Not Play  (Rainy, dan Suhu Hot)
{model.predict([[1,2]])} <- Not Play  (Rainy, dan Suhu Mild)

____________________________________________________________

""")


____________________________________________________________

Berdasarkan model Random Forest kita (n_estimator =10)

Prediksi Machine Learning Random Fores dengan input 
cuaca Rainy,Overcast, dan Suhu Mild, Hot

1 = Play, 0 = No

[1] <- Play      (Overcast, dan Suhu Mild)
[1] <- Play      (Overcast, dan Suhu Hot)
[0] <- Not Play  (Rainy, dan Suhu Hot)
[1] <- Not Play  (Rainy, dan Suhu Mild)

____________________________________________________________




In [ ]:
#SVM

from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn import metrics

X = features
y = label

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.8, random_state=1)

model = svm.SVC(kernel='linear')
model = model.fit(X_train,y_train)
y_pred = model.predict(X_test)

print(f"""
____________________________________________________________

Berdasarkan model SVM kita (n_estimator =100)

Prediksi Machine Learning SVM dengan input 
cuaca Rainy,Overcast, dan Suhu Mild, Hot

1 = Play, 0 = No

{model.predict([[0,2]])} <- Play      (Overcast, dan Suhu Mild)
{model.predict([[0,1]])} <- Play      (Overcast, dan Suhu Hot)
{model.predict([[1,1]])} <- Not Play  (Rainy, dan Suhu Hot)
{model.predict([[1,2]])} <- Play      (Rainy, dan Suhu Mild)

____________________________________________________________

""")


____________________________________________________________

Berdasarkan model SVM kita (n_estimator =100)

Prediksi Machine Learning SVM dengan input 
cuaca Rainy,Overcast, dan Suhu Mild, Hot

1 = Play, 0 = No

[1] <- Play      (Overcast, dan Suhu Mild)
[1] <- Play      (Overcast, dan Suhu Hot)
[0] <- Not Play  (Rainy, dan Suhu Hot)
[1] <- Play      (Rainy, dan Suhu Mild)

____________________________________________________________




Ketika kita sudah menentukan model machine learning mana yang paling baik maka kita akan melakuka deploy ke production. menggunakan Pickle dan Cloud (Optional)

In [ ]:
import numpy as np
import pickle

#yang terbaik adalah Random Forest maka akan dibuat Pickle file (.pkl)

model = RandomForestClassifier(n_estimators=10)
model = model.fit(X_train,y_train)


pickle.dump(model,open('model_classifier_terbaik.pkl','wb'))

In [ ]:
model_load = pickle.load(open('model_classifier_terbaik.pkl','rb'))

print(f"""
____________________________________________________________

Berdasarkan model *terbaik* kita (n_estimator =100)

Prediksi Machine Learning dengan input 
cuaca Rainy,Overcast, dan Suhu Mild, Hot

1 = Play, 0 = No

{model.predict([[0,2]])} <- Play      (Overcast, dan Suhu Mild)
{model.predict([[0,1]])} <- Play      (Overcast, dan Suhu Hot)
{model.predict([[1,1]])} <- Not Play  (Rainy, dan Suhu Hot)
{model.predict([[1,2]])} <- Not Play  (Rainy, dan Suhu Mild)

____________________________________________________________

""")


____________________________________________________________

Berdasarkan model *terbaik* kita (n_estimator =100)

Prediksi Machine Learning dengan input 
cuaca Rainy,Overcast, dan Suhu Mild, Hot

1 = Play, 0 = No

[1] <- Play      (Overcast, dan Suhu Mild)
[1] <- Play      (Overcast, dan Suhu Hot)
[0] <- Not Play  (Rainy, dan Suhu Hot)
[0] <- Not Play  (Rainy, dan Suhu Mild)

____________________________________________________________


